version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies
      - bundle install
  build:
    commands:
      - echo Starting database update/create
      - CONFIGURATION=true bundle exec rails db:create
      - CONFIGURATION=true bundle exec rails db:migrate
      - CONFIGURATION=true bundle exec rails db:seed
  post_build:
    commands:
      - echo Finished migrations