version: '2.1'

# ACTUAL CONFIGURATION
services:
  # DATABASE CONFIGURATION
  psql:
    command: postgres -c logging_collector=on
      -c log_min_duration_statement=0
      -c log_directory='/var/log/postgresql'
      -c log_min_messages='WARNING'
      -c log_rotation_age='1d'
      -c log_rotation_size='1GB'
    container_name: pierpontglobal-psql
    hostname: psql
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'qusUt1i9obru4ISTUG2f'
    ports:
      - "5432:5432"
    volumes:
      - psql:/var/log/postgresql
    networks:
      - elk
      - api

  elasticsearch:
    container_name: pierpontglobal-elasticsearch
    build:
      context: config/docker/elasticsearch/
    volumes:
      - ./config/docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
    - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - elk

  kibana:
    container_name: pierpontglobal-kibana
    build:
      context: config/docker/kibana/
    volumes:
    - ./config/docker/kibana/config/:/usr/share/kibana/config:ro
    ports:
    - "5601:5601"
    networks:
    - elk
    depends_on:
    - elasticsearch

  redis:
    user: root
    restart: always
    command: '--logfile /var/log/redis/redis-server.log'
    container_name: pierpontglobal-redis
    build:
      context: config/docker/redis
    logging:
      driver: "json-file"
    volumes:
      - redis:/var/log/redis
    ports:
    - '6379:6379'
    networks:
    - api

  sidekiq:
    user: root
    build:
      context: .
      dockerfile: sidekiq.dockerfile
    environment:
      - DB_HOST=psql
      - DB_PASSWORD=qusUt1i9obru4ISTUG2f
      - DB_USER=postgres
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - JOB_WORKER_URL=redis://redis:6379/0
      - QUEUENAME=car_pulling
      - SLAVE=true
      - MACHINE=linuxdock
    networks:
      - api
      - elk

  rails:
    restart: always
    user: root
    container_name: pierpontglobal-api
    build: .
    volumes:
      - .:/pierpontglobal-api
    environment:
      - DB_HOST=psql
      - DB_PASSWORD=qusUt1i9obru4ISTUG2f
      - DB_USER=postgres
      - JOB_WORKER_URL=redis://redis:6379/0
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - STRIPE_KEY=sk_test_D1EcOcPXzM1XkpDUo7dQnQF0
      - PORT=3000
      - AWS_REGION=us-east-1
      - AWS_BUCKET=pierpontglobal-api-images
      - AWS_ACCESS_KEY_ID=AKIAI566CCS72L4YKO4A
      - AWS_SECRET_ACCESS_KEY=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
      - MACHINE=linux
    ports:
      - "3000:3000"
    networks:
      - api
      - elk
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:3000 || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 5
    depends_on:
      elasticsearch:
        condition: service_healthy


networks:
  elk:
    driver: bridge
  api:
    driver: bridge

volumes:
  psql:
    driver: local
  nginx:
    driver: local
  redis:
    driver: local